### ISSUE TITLE
Issue when uploading new users

### ISSUE THREAD

**Issue by heathdbrown** [trogers-twilio/script-taskrouter-bulk-workers#1]
I was able to attempt to load the CSV and it loads the numbers of users then fails when attempting to create the users.

```
Would you like to proceed? (Y or N): Y

(node:7718) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at escapeNonAlphaChars (/home/brownhd/Projects/script-taskrouter-bulk-workers/createupdate.js:27:34)
    at generateContactUri (/home/brownhd/Projects/script-taskrouter-bulk-workers/createupdate.js:35:20)
    at createWorkers (/home/brownhd/Projects/script-taskrouter-bulk-workers/createupdate.js:121:20)
    at sortWorkersToLoad (/home/brownhd/Projects/script-taskrouter-bulk-workers/createupdate.js:89:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7718) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:7718) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by trogers-twilio** [comment]
@heathdbrown Hello Heath. The first thing I would check is the CSV file you're importing in a text editor instead of a spreadsheet tool like Excel and make sure every row has a valid `friendlyName` defined. The error happening with the `.replace()` method would indicate the value being passed in as the `stringToEscape` is an `undefined` value, which should only happen if somehow the CSV has an entry, or multiple entries, without a `friendlyName` string.

**Comment by heathdbrown** [comment]
I noticed when I was working with this over the weekend that one of the email address had a '-', the regex pattern I copied from the Internet does not have this as a valid character.
